automate/users/routes.py
import os
from datetime import datetime, date
from flask import Blueprint, render_template, flash, request, redirect, url_for, abort, jsonify, current_app
from automate import db, mail, bcrypt
from flask_mail import Message
from flask_login import login_required, login_user, logout_user, current_user
from automate.users.forms import SignupForm, LoginForm, ForgetPasswordForm, PasswordResetForm, NewUserForm, ProfileForm
from automate.models import User, Activitylog, Feeditem, Feedtype, Vendor, Farmitem, Pen, Customer
from automate.users.utils import save_picture, send_reset_email
from automate.feedmill.utils import numberMonth

users = Blueprint('users', __name__)

# Template Filter
@users.app_template_filter()
def extractTwoWords(value):
    new_list = value.split()
    return new_list[0] +' '+ new_list[1]

# Login Route
@users.route('/', methods=['GET', 'POST'])
@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('users.portal'))
    form = LoginForm()
    if form.validate_on_submit():
        theuser = User.query.filter_by(email=form.email.data).first()
        if theuser and bcrypt.check_password_hash(theuser.password, form.password.data):
            login_user(theuser, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.portal'))
        else:
            flash('Invalid Login Credentials!', 'danger')
            return redirect(url_for('users.login'))

    return render_template("main/index.html", title = "Login", form = form)


# NewUser Route
@users.route('/users', methods=['GET', 'POST'])
def user():
    form = NewUserForm()
    if form.validate_on_submit():
        email = form.email.data
        user_row = User.query.filter_by(email=email).first()
        if user_row:
            flash('Email already Exist', 'danger')
        else:
            user = User(email=form.email.data, role=form.role.data)

            try:
                #Send email
                msg = Message(subject='Management system', sender=('County Choice Farms', 'menaelvisjones@gmail.com'), recipients=[email])
                msg.body = f'''Hi, Welcome to County Choice Management System, to complete user registration, kindly follow the link below:\n{ url_for('users.signup', email=email, _external = True) }
                
Ignore, if you didn't request for management portal role. 
                '''
                mail.send(msg)

            except:
                flash('Problem Sending Mail, check internet connection!', 'warning')
                return (redirect(url_for('users.user')))
                
            db.session.add(user)
            db.session.commit()
            flash('User added successfully', 'success')


    # Handle update user role form processing
    if request.method == 'POST' and request.form.get('check') == 'edit_user':
        userId = request.form.get('userId')
        userEmail = request.form.get('userEmail')
        userRole = request.form.get('role')

        checkemail = User.query.filter(User.email == userEmail).first()
        if checkemail:
            _ = User.query.filter(User.id == userId).update({'role': userRole})
            db.session.commit()

            flash('User role updated successfully', 'success')
            return redirect(url_for('users.user'))
        
        else:
            flash('Please check user email', 'warning')

    
     # Handle Delete user form processing
    if request.method == 'POST' and request.form.get('check') == 'delete_user':
        delete_id = request.form.get('delete_user_id')
        user_password = request.form.get('password')

        user_row = User.query.filter(User.id == delete_id).first()
        if user_row and bcrypt.check_password_hash(current_user.password, user_password):
            db.session.delete(user_row)
            db.session.commit()

            flash('User deleted successfully', 'success')
            return redirect(url_for('users.user'))            
        else:
            flash('Please check your password and try again', 'warning')
            return redirect(url_for('users.user')) 

    # Fetch all pending notifications
    all_activities = Activitylog.query.filter(Activitylog.status == 'pending').\
                            order_by(Activitylog.id.desc()).limit(3).all()

    # Fetch all User specific notifications
    user_activities = Activitylog.query.filter(Activitylog.user_id == current_user.id, Activitylog.status == 'pending').\
                            order_by(Activitylog.id.desc()).limit(3).all()

    # Fetch All Users
    users = User.query.filter(User.username != None).all()
    # Fetch User Image
    image_file = url_for('static', filename='wt-profile-pics/'+current_user.picture)

    return render_template("main/users.html", title = "Users", form = form, ficon = "users", date = datetime.now(), 
            image_file=image_file, users=users, all_activities=all_activities, user_activities=user_activities)


# Handle update user role form population
@users.route('/update_userrole', methods=['POST'])
def update_user():
    user_id = request.get_data('id').decode('utf-8')
    user_id = int(user_id)
    user_row = User.query.filter(User.id == user_id).first()

    userList = []
    userDict = {}

    userDict['id'] = user_row.id
    userDict['email'] = user_row.email
    userList.append(userDict)

    return jsonify({'userData': userList})


# Handle update user role form population
@users.route('/delete_user', methods=['POST'])
def delete_user():
    user_id = request.get_data('id').decode('utf-8')
    user_id = int(user_id)
    user_row = User.query.filter(User.id == user_id).first()

    userList = []
    userDict = {}

    userDict['id'] = user_row.id
    userDict['username'] = user_row.username
    userList.append(userDict)

    return jsonify({'user_data': userList})


# Signup Route
@users.route('/signup/<email>', methods=['GET', 'POST'])
def signup(email):
    if current_user.is_authenticated:
        return redirect(url_for('users.portal'))
    form = SignupForm()
    form.email.data = email
    if form.validate_on_submit():
        check_email = User.query.filter(User.email==form.email.data).first()
        if check_email:
            hash_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            check_email.username = form.username.data
            check_email.password = hash_pwd
            db.session.commit()
            flash('SignUp was successful. Please Login!', 'success')
            return redirect(url_for('users.login'))
        else:
            flash('Please check the email link', 'danger')
    return render_template("main/wt_signup.html", title="Signup", form=form)


# ForgetPassword Route
@users.route('/forgetpassword', methods=['GET', 'POST'])
def forgetPassword():
    if current_user.is_authenticated:
        return redirect(url_for('users.portal'))
    form = ForgetPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to you, with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template("main/wt_forget_password.html", title = "Forget Password", form = form)


# ResetPassword Route
@users.route('/resetpassword/<token>', methods=['GET', 'POST'])
def resetPassword(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.portal'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Email reset token has expired or is invalid, reset again!', 'warning')
        return redirect(url_for('users.forgetPassword'))
    form = PasswordResetForm()
    if form.validate_on_submit():
        hash_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hash_pwd
        db.session.commit()
        flash('Password Reset Successful', 'success')
        return redirect(url_for('users.login'))
    return render_template("main/wt_password_reset.html", title = "Reset Password", form = form)


# Profile Route
@users.route('/user_profile', methods=['GET', 'POST'])
@login_required
def profile():
    c_user = current_user.username
    image_file = url_for('static', filename='wt-profile-pics/'+current_user.picture)
    form = ProfileForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.picture = picture_file
        current_user.firstname = form.firstname.data
        current_user.lastname = form.lastname.data
        current_user.username = form.username.data
        db.session.commit()

        flash('Profile Updated Successfully', 'success')
        return redirect(url_for('users.profile'))

    if request.method =='GET':
        if current_user.firstname is None:
            pass
        else:
            form.firstname.data = current_user.firstname

        if current_user.lastname is None:
            pass
        else:
            form.lastname.data = current_user.lastname
        
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.role.data = current_user.role

    return render_template("main/profile.html", title = c_user, ficon = "user", form=form, date = datetime.now(), image_file=image_file)


# ManagementPortal Route
@users.route('/management_portal')
@login_required
def portal():
    image_file = url_for('static', filename='wt-profile-pics/'+current_user.picture)
    return render_template("main/portal.html", title = "Portal", image_file=image_file)


# Notification Route
@users.route('/notifications', methods=['GET', 'POST'])
def notifications():

    # Handle Request Authorization Processing

automate/templates/macros/fields.html
<!-- WITH ICON -->
{% macro render_field(icon, field) %}
<div class="form-group">
    <div class="help-block white-text mb-1 font-small">{{ field.label.text }}</div>

    <div class="input-group">
        <div class="input-group-prepend w-100">
            <div class="input-group-text">
                <i class="fas fa-{{ icon }} teal-text"></i>
            </div>
            {{ field(class_='form-control', **kwargs)| safe }}
        </div>
    </div>
    {% if field.errors %}
    {% for error in field.errors %}
    <div class="font-small text-danger" style="margin-top:5px; margin-bottom:-5px;">{{ error }}</div>
    {% endfor %}
    {% endif %}
</div>
{% endmacro %}

<!-- WITHOUT ICON -->
{% macro render_form(field) %}
<div class="form-group">

    <div class="help-block blue-grey-text mb-1 font-small">{{ field.label.text }}</div>

    {% if field.errors %}
    {% for error in field.errors %}
    <div class="input-group">
        {{ field(class_='form-control is-invalid', **kwargs)| safe }}
    </div>
    <div class="font-small text-danger" style="margin-top:5px; margin-bottom:-5px;">{{ error }}</div>
    {% endfor %}
    {% else %}
    <div class="input-group">
        {{ field(class_='form-control', **kwargs)| safe }}
    </div>
    {% endif %}

</div>
{% endmacro %}

{% macro profile_form(field) %}
<div class="form-group mt-3">
    <div class="row">
        <div class="col-md-3">
            <div class="help-block blue-grey-text mt-2 font-small">{{ field.label.text }}:</div>
        </div>
        <div class="col-md-9">
            {% if field.errors %}
            {% for error in field.errors %}
            <div class="input-group">
                {{ field(class_='form-control is-invalid', **kwargs)| safe }}
            </div>
            <div class="font-small text-danger" style="margin-top:5px; margin-bottom:-5px;">{{ error }}</div>
            {% endfor %}
            {% else %}
            <div class="input-group">
                {{ field(class_='form-control', **kwargs)| safe }}
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endmacro %}

automate/templates/macros/sidenav.html
<!-- Feedmill SideNav -->
{% macro feedmill() %}
<li><a href="{{ url_for('feedmill.feedoverview') }}" class="white-text"><i class="fas fa-tachometer-alt"></i> &nbsp;
        Overview</a>
</li>
<li><a href="{{ url_for('feedmill.feedinventory') }}" class="white-text"><i class="fas fa-store"></i> &nbsp;
        Inventory</a></li>
<li><a href="{{ url_for('feedmill.feedproduction') }}" class="white-text"><i class="fas fa-industry"></i> &nbsp;
        Production</a></li>
<li><a href="{{ url_for('feedmill.feedtypes') }}" class="white-text"><i class="fas fa-boxes"></i> &nbsp; Feed Type</a>
</li>
<li><a href="{{ url_for('feedmill.feedcost') }}" class="white-text">&#8358; &nbsp; Feed Cost</a>
</li>
<li><a href="{{ url_for('users.notifications') }}" class="white-text"><i class="fas fa-bell"></i> &nbsp; Notifications</a> 
        {% if current_user.role == 'Admin' %}
                {% if all_activities %}
                        <span class="badge badge-pill badge-warning">{{ all_activities | length }}</span> 
                {% endif %}
        {% else %}
                {% if user_activities %}
                        <span class="badge badge-pill badge-warning">{{ user_activities | length }}</span> 
                {% endif %}
        {% endif %}
</li>

{% if current_user.role == 'Admin' %}
</li>
<li><a href="{{ url_for('users.user') }}" class="white-text"><i class="fas fa-users"></i> &nbsp; Users mgt.</a>
</li>
{% endif %}

<li style="position: absolute; top: 115%; border-width: 0px;"><a href="{{ url_for('users.portal') }}"
        class="white-text"><i class="fas fa-arrow-left"></i>
        &nbsp; Portal</a>
</li>
{% endmacro %}
<!-- Feedmill SideNav -->

<!-- Store SideNav -->
{% macro store() %}
<li><a href="{{ url_for('stores.store_overview') }}" class="white-text"><i class="fas fa-tachometer-alt"></i> &nbsp;
        Overview</a>
</li>
<li><a href="{{ url_for('stores.store_vendors') }}" class="white-text"><i class="fas fa-users"></i> &nbsp;
        Vendors</a></li>
<li><a href="{{ url_for('stores.store_purchases', purchase='feed_purchase') }}" class="white-text">&#8358; &nbsp;
        Purchases</a></li>
<li><a href="{{ url_for('stores.store_stock') }}" class="white-text"><i class="fas fa-industry"></i> &nbsp;
        Feed Stock</a></li>
<li><a href="{{ url_for('stores.store_receivables') }}" class="white-text"><i class="fas fa-shopping-cart"></i> &nbsp;
        Receivables</a></li>
<li><a href="{{ url_for('users.notifications') }}" class="white-text"><i class="fas fa-bell"></i> &nbsp; Notifications</a> 
        {% if current_user.role == 'Admin' %}
                {% if all_activities %}
                        <span class="badge badge-pill badge-warning">{{ all_activities | length }}</span> 
                {% endif %}
        {% else %}
                {% if user_activities %}
                        <span class="badge badge-pill badge-warning">{{ user_activities | length }}</span> 
                {% endif %}
        {% endif %}
</li>

{% if current_user.role == 'Admin' %}
<li><a href="{{ url_for('users.user') }}" class="white-text"><i class="fas fa-users"></i> &nbsp; Users mgt.</a>
</li>
{% endif %}

<li style="position: absolute; top: 115%; border-width: 0px;"><a href="{{ url_for('users.portal') }}"
        class="white-text"><i class="fas fa-arrow-left"></i>
        &nbsp; Portal</a>
</li>
{% endmacro %}
<!-- Store SideNav -->

<!-- Eggtore Sidenav -->
{% macro eggstore() %}
<li><a href="{{ url_for('stores.eggstore_overview') }}" class="white-text"><i class="fas fa-tachometer-alt"></i> &nbsp;
        Overview</a>
</li>
<li><a href="{{ url_for('stores.eggstore_customers') }}" class="white-text"><i class="fas fa-users"></i> &nbsp;
        Customers</a></li>
<li><a href="{{ url_for('stores.eggstore_stock') }}" class="white-text"><i class="fas fa-users"></i> &nbsp;
        Egg Stock</a></li>
<li><a href="{{ url_for('stores.eggstore_supply') }}" class="white-text"><i class="fas fa-industry"></i> &nbsp;
        Egg Supply</a></li>
<li><a href="{{ url_for('users.notifications') }}" class="white-text"><i class="fas fa-bell"></i> &nbsp; Notifications</a> 
        {% if current_user.role == 'Admin' %}
                {% if all_activities %}
                        <span class="badge badge-pill badge-warning">{{ all_activities | length }}</span> 
                {% endif %}
        {% else %}
                {% if user_activities %}
                        <span class="badge badge-pill badge-warning">{{ user_activities | length }}</span> 
                {% endif %}
        {% endif %}
</li>

{% if current_user.role == 'Admin' %}
<li><a href="{{ url_for('users.user') }}" class="white-text"><i class="fas fa-users"></i> &nbsp; Users mgt.</a>
</li>
{% endif %}

<li style="position: absolute; top: 115%; border-width: 0px;"><a href="{{ url_for('users.portal') }}"
        class="white-text"><i class="fas fa-arrow-left"></i>
        &nbsp; Portal</a>
</li>
{% endmacro %}
<!-- Eggtore Sidenav -->

<!-- Profile SideNav -->
{% macro profile() %}
<li><a href="#" class="white-text"><i class="fas fa-users"></i> &nbsp; Human Resources</a>
</li>
<li><a href="{{ url_for('feedmill.feedoverview') }}" class="white-text"><i class="fas fa-tachometer-alt"></i> &nbsp;
        Feed
        Cost mgt.</a>
</li>
<li><a href="#" class="white-text"><i class="fas fa-industry"></i> &nbsp;
        Procurement mgt.</a></li>
<li><a href="#" class="white-text"><i class="fas fa-shopping-cart"></i> &nbsp;
        Sales mgt.</a></li>
<li><a href="{{ url_for('stores.store_portal') }}" class="white-text"><i class="fas fa-boxes"></i> &nbsp; Store mgt.</a>
</li>
{% if current_user.role == 'Admin' %}
<li><a href="{{ url_for('users.user') }}" class="white-text"><i class="fas fa-users"></i> &nbsp; Users mgt.</a>
</li>
{% endif %}

{% endmacro %}
<!-- Profile SideNav -->