automate/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, SelectField
from wtforms.validators import InputRequired, Length, Email, EqualTo, ValidationError
from automate.models import User


class NewUserForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(message='Field is Required'),
                Email(message='Invalid Email')])
    role = SelectField('Role', choices=[('', 'Select User Role'),
                ('Admin','Admin'), ('Viewer', 'Viewer'), ('Account','Account'), ('Procurement','Procurement'), ('Sales','Sales'), ('Feedmill','Feedmill'), ('Store','Store'), ('Egg-Store','Egg-Store'), ('Human Resource','Human Resource')])
    submit = SubmitField('ADD USER')

class SignupForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(message='Field is Required'),
                Email(message='Invalid Email')])
    username = StringField('Username', validators=[InputRequired(message='Field is Required'),
                Length(min=6, message='Username is too short')])
    password = PasswordField('Password', validators=[
                InputRequired(message='Field is Required'), Length(min=6, message='Password must be at least 6 characters')])
    submit = SubmitField('SIGNUP')

    def validate_username(self, username):
        user_check = User.query.filter_by(username=username.data).first()
        if user_check:
            raise ValidationError('Username already Exist')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(message='Field is Required'),
                Email(message='Invalid Email')])
    password = PasswordField('Password', validators=[
                InputRequired(message='Field is Required'), Length(min=6, message='Password must be at least 6 characters')])
    remember = BooleanField('Remember Me')
    submit = SubmitField('LOGIN')

class ForgetPasswordForm(FlaskForm):
    email = StringField('Email', validators=[InputRequired(message='Field is Required'),
                Email(message='Invalid Email')])
    submit = SubmitField('RETRIEVE')

    def validate_email(self, email):
        email_check = User.query.filter_by(email=email.data).first()
        if email_check is None:
            raise ValidationError('Email does not exist')

class PasswordResetForm(FlaskForm):
    password = PasswordField('Password', validators=[
                InputRequired(message='Field is Required'), Length(min=6, max=12, message='Password must be at least 6 characters')])
    confirm_password = PasswordField('Confirm Password',
                validators=[InputRequired(message='Field is Required'), EqualTo('password')])
    submit = SubmitField('RESET')

class ProfileForm(FlaskForm):
    firstname = StringField('Firstname')
    lastname = StringField('Lastname')
    email = StringField('Email')
    username = StringField('Username', validators=[InputRequired(message='Field is Required'),
                Length(min=6, message='Username is too short')])
    role = StringField('Role')
    picture = FileField('Profile Picture', validators=[FileAllowed(['jpg','png','jpeg','JPEG', 'JPG'])])
    submit = SubmitField('UPDATE')

automate/stores/routes.py
import os
from datetime import datetime, date, timedelta
from flask import Blueprint, render_template, flash, request, redirect, url_for, jsonify, abort, current_app
from automate import db, Mail
from flask_mail import Message
from flask_login import login_required, current_user
from automate.stores.forms import storeForm, eggstoreForm
from automate.models import Activitylog, Feeditem, Feedstock, Feedtype, Vendor, Farmitem, Purchase, Production, Receivable, Formulation, Feedcost, Customer, Pen, Allocation, Eggsale, Eggstock
from automate.feedmill.utils import (update, wordTruncate, numberDecreament, numberDecimal, numberFormat, numberMonth, 
                                    color_sample, receivable_update, updateproduction, tonnesToBag, eggstock_update)

stores = Blueprint('stores', __name__)

# STORE PORTAL ROUTE
@stores.route('/storemgt/store_portal')
@login_required
def store_portal():
    image_file = url_for('static', filename='wt-profile-pics/'+current_user.picture)
    return render_template('storemgt/store_portal.html', title='Store Portal', image_file=image_file)


# STORE OVERVIEW ROUTE
@stores.route('/storemgt/store_overview', methods=['GET', 'POST'])
@login_required
def store_overview():
    # call update function
    update()
    # run update production
    updateproduction()
    # Receivable update
    receivable_update()
    # Eggstock Update
    eggstock_update()

    # Fetch Closing Stock of feed produced
    closing_production = Production.query.filter(Production.date == date.today()).all()
    if closing_production:
        prod_colors = color_sample(int(closing_production[-1].feedtype_id) + 1)
    else:
        prod_colors = 0


    # Fetch Closing Stock of feed item
    all_feedstock = Feedstock.query.filter(Feedstock.date == date.today()).all()
    if all_feedstock:
        stock_colors_qty = color_sample(int(all_feedstock[-1].feeditem_id) + 1)
        stock_colors_price = color_sample(int(all_feedstock[-1].feeditem_id) + 1)
    else:
        stock_colors_qty = 0
        stock_colors_price = 0

    
    # Fetch the available farm item
    all_farmitem = Receivable.query.filter(Receivable.date == date.today(), Receivable.c_qty !=0).all()
    if all_farmitem:
        farmitem_colors = color_sample(int(all_farmitem[-1].farmitem_id) + 1)
    else:
        farmitem_colors = 0


    # Fetch all pending notifications
    all_activities = Activitylog.query.filter(Activitylog.status == 'pending').\
                            order_by(Activitylog.id.desc()).limit(3).all()

    # Fetch all User specific notifications
    user_activities = Activitylog.query.filter(Activitylog.user_id == current_user.id, Activitylog.status == 'pending').\
                            order_by(Activitylog.id.desc()).limit(3).all()

    # Current user Image
    image_file = url_for('static', filename='wt-profile-pics/'+current_user.picture)

    return render_template('storemgt/store_overview.html', title='Store Overview', ficon="store", date=datetime.now(), closing_production=closing_production,
                           prod_colors=prod_colors, all_feedstock=all_feedstock, stock_colors_qty=stock_colors_qty, stock_colors_price=stock_colors_price, all_farmitem=all_farmitem,
                           farmitem_colors=farmitem_colors, image_file=image_file, all_activities=all_activities, user_activities=user_activities)


# STORE VENDORS ROUTE
@stores.route('/storemgt/store_vendors', methods=['GET', 'POST'])
@login_required
def store_vendors():
    # Update Receivable db
    receivable_update()

    # instantiate the store form
    form = storeForm()


    # Handle Processing of New Vendor
    if request.method == 'POST' and request.form.get('check') == 'add_vendor':
        vendor_name = request.form.get('vendor')
        vendor_name = vendor_name.title()

        # Check if vendor name exist in vendor db
        check_vendor_name = Vendor.query.filter(Vendor.vendor == vendor_name).first()
        if check_vendor_name:
            flash(vendor_name+' already exist in database, please rename', 'warning')
        else:
            new_vendor = Vendor(vendor = vendor_name)
            db.session.add(new_vendor)
            db.session.commit()

            flash(vendor_name+' added successfully', 'success')
            return redirect(url_for('stores.store_vendors'))


    # Handle processing of rename vendor form
    if request.method == 'POST' and request.form.get('check') == 'rename_vendor':
        vendor_id = request.form.get('vendorId')
        old_vendor_name = request.form.get('old_vendor_name')
        new_vendor_name = request.form.get('new_vendor_name')
        new_vendor_name = new_vendor_name.title()

        # Check if name exist in vendor db
        check_new_name = Vendor.query.filter(Vendor.vendor == new_vendor_name).first()
        if new_vendor_name == old_vendor_name:
            flash('New vendor name is the same as Old name', 'warning')
        elif check_new_name:
            flash(new_vendor_name+' already exist in database', 'warning')
        else:
            _ = Vendor.query.filter(Vendor.id == vendor_id).update({'vendor': new_vendor_name})
            db.session.commit()

            flash('Vendor renamed successfully', 'success')
            return redirect(url_for('stores.store_vendors'))


    # Handle Processing of delete Vendor Form
    if request.method == 'POST' and request.form.get('check') == 'delete_vendor':
        # Get vemdor id
        vendor_delete_id = request.form.get('vendor_delete_id')

        # Get vendor id row
        vendor_data = Vendor.query.filter(Vendor.id == vendor_delete_id).first()

        # Get user info and activities
        user = current_user.id
        user_activity = 'Delete Request for Vendor - '+vendor_data.vendor+' Received'
        request_query = 'Vendor of id '+vendor_delete_id

        # Add Data to the Activitylog database
        new_activity = Activitylog(user_id = user, activity = user_activity, request = request_query)
        db.session.add(new_activity)
        db.session.commit()

        flash('Delete Request for '+ vendor_data.vendor +' Sent', 'success')
        return redirect(url_for('stores.store_vendors'))

        
    # Handle processing of New Farm item
    if request.method == 'POST' and request.form.get('check') == 'add_farmitem':
        farmitem_name = request.form.get('farmitem')
        farmitem_name = farmitem_name.capitalize()

        # Check if Farmitem exists in the farmitem db
        check_farmitem =  Farmitem.query.filter(Farmitem.item == farmitem_name).first()
        if check_farmitem:
            flash(farmitem_name+' already exists in database, please rename', 'warning')
        else:
            new_farmitem = Farmitem(item = farmitem_name)
            db.session.add(new_farmitem)
            db.session.commit()

            # Update the receivable db
            # Check if the new farmitem exists in Receivable db
            check_receivable = Receivable.query.filter(Receivable.date == date.today(), Receivable.farmitem_id == new_farmitem.id).first()
            if check_receivable:
                pass
            else:
                new_receivable_item = Receivable(farmitem_id=new_farmitem.id)
                db.session.add(new_receivable_item)
                db.session.commit() 

            flash(farmitem_name+' added successfully', 'success')
            return redirect(url_for('stores.store_vendors'))


    # Handle processing for rename farmitem form
    if request.method == 'POST' and request.form.get('check') == 'rename_farmitem':
        farmitem_id = request.form.get('farmitemId')
        old_farmitem_name = request.form.get('old_farmitem_name')
        new_farmitem_name = request.form.get('new_farmitem_name')
        new_farmitem_name = new_farmitem_name.capitalize()

        # Check if farmitem exist in farmitem db
        check_farmitem_name = Farmitem.query.filter(Farmitem.item == new_farmitem_name).first()
        if new_farmitem_name == old_farmitem_name:
            flash('New farm item name is the same as the Old name', 'warning')
        elif check_farmitem_name:
            flash(new_farmitem_name+' already exist in database', 'warning')
        else:
            _ = Farmitem.query.filter(Farmitem.id == farmitem_id).update({'item': new_farmitem_name})
            db.session.commit()

            flash('Farmitem renamed successfully', 'success')
            return redirect(url_for('stores.store_vendors'))


    # Handle Processing of delete farmitem Form
    if request.method == 'POST' and request.form.get('check') == 'delete_farmitem':
        # Get farmitem id
        farmitem_delete_id = request.form.get('farmitem_delete_id')

        # Get farmitem id row
        farmitem_data = Farmitem.query.filter(Farmitem.id == farmitem_delete_id).first()

        # Get user info and activities
        user = current_user.id
        user_activity = 'Delete Request for Farmitem - '+farmitem_data.item+' Received'
        request_query = 'Farmitem of id '+farmitem_delete_id

        # Add Data to the Activitylog database
        new_activity = Activitylog(user_id = user, activity = user_activity, request = request_query)
        db.session.add(new_activity)
        db.session.commit()

        flash('Delete Request for '+ farmitem_data.item +' Sent', 'success')
        return redirect(url_for('stores.store_vendors'))


    # Fetch all vendors list in vendor db
    vendor_list = Vendor.query.all()
    if vendor_list:
        vendor_color = color_sample(int(vendor_list[-1].id) + 1)
    else:
        vendor_color = 0


    # Fetch all farm items in farm item db
    farmitem_list = Farmitem.query.all()
    if farmitem_list:
        farmitem_color = color_sample(int(farmitem_list[-1].id) + 1)
    else:
        farmitem_color = 0


    # Fetch all pending notifications
    all_activities = Activitylog.query.filter(Activitylog.status == 'pending').\

automate/templates/main/index.html
{% extends "layout/layout1.html" %}
{% from "macros/fields.html" import render_field %}

{% block formcontent %}

<div class="col-md-6 offset-md-3">

    <!-- Alert Box -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} mt-4">
        <span class="font-weight-bold">{{message}}</span>
        <a href="javascript:void(0)" data-dismiss="alert" class="close">&times;</a>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="mt-3 z-depth-1-half p-3 form-box">
        <div class="white-text font-weight-bold mb-2 login-text">LogIn
            to
            Dashboard</div>

        <!-- Horizontal line -->
        <hr class="hr-light">

        <form action="" method="post" id="loginForm">
            {{ form.csrf_token }}
            <!--Email -->
            {{ render_field('envelope', form.email, placeholder='Enter Your Email...') }}

            <!-- Password -->
            {{ render_field('key', form.password, placeholder='Enter Your Password...') }}

            <!-- Remember Me -->
            <div class="form-group form-check">
                {{ form.remember(class="form-check-input form-check-inline") }}
                {{ form.remember.label(class="help-block white-text mb-1 font-small") }}
            </div>

            <!-- Submit -->
            <div class="form-group">
                {{ form.submit(class="form-control teal darken-2 white-text font-weight-bold") }}
            </div>
        </form>

        <!-- forget password -->
        <a href="{{ url_for('users.forgetPassword') }}" class="white-text font-small fpass">Forget Password?</a>
    </div>

</div>

{% endblock formcontent %}

automate/templates/main/portal.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/lykmapipo/themify-icons@0.1.2/css/themify-icons.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='wt-css/wt-main.css')}}">
    <link rel="icon" href="{{url_for('static', filename='wt-design/favicon.png')}}">

    {% if title %}
    <title>{{ title }} - Management System</title>
    {% else %}
    <title>Management System</title>
    {% endif %}

</head>

<body>

    <!-- Main -->
    <div class="portal pt-3">

        <!-- Header -->
        <div class="container">
            <div class="row">
                <div class="col-md-12 d-flex justify-content-between">
                    <div class="logo">
                        <img src="{{url_for('static', filename='wt-design/favicon.png')}}" class="img" alt="logo">
                    </div>
                    <div class="profile d-flex align-items-center flex-row">
                        <div class="profile-info mr-3 font-small">
                            <span class="font-weight-bold">Hi, <a href="javascript: void(0)"
                                    class="black-text font-weight-normal user-name">
                                    {% if current_user.firstname and current_user.lastname %}
                                    {{ current_user.firstname +" "+ current_user.lastname  }}
                                    {% else %}
                                    {{ current_user.username }}
                                    {% endif %}
                                </a>
                            </span>
                            <!-- Dropdown -->
                            <ul class="list-unstyled p-2 more z-depth-1">
                                <li class="font-small"> <a href="{{ url_for('users.profile') }}" class="text-dark"><i
                                            class="fas fa-user teal-text"></i>
                                        Profile</a> </li>
                                <li class="font-small"><a href="{{ url_for('users.logout') }}" class="text-dark"><i
                                            class="fas fa-power-off text-danger"></i>
                                        LogOut</a> </li>
                            </ul>
                        </div>
                        <div class="profile-img rounded-circle z-depth-1">
                            <img src="{{ image_file }}" alt="{{ current_user.username }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header -->

        <!-- Welcome Alert -->
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center font-weight-bold system-name mdb-color-text">
                    County Choice Management System
                </div>
                <div class="col-md-12 mt-3 welcome-alert">
                    <div class="alert alert-success">
                        Welcome to County Choice Management System Portal
                        <a href="javascript: void(0)" class='close font-small' data-dismiss="alert">&times;</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Welcome Alert -->

        <!-- Portals -->
        <div class="container">
            <div class="row">
                <div class="col-md-10 offset-md-1">
                    <div class="portal-box d-flex justify-content-around align-items-center flex-wrap">

                        <!-- First Box -->
                        <div class="box-1 z-depth-1-half aqua-gradient d-flex flex-column align-items-center">
                            <div class="box-img mt-3">
                                <a href="#"><img src="{{ url_for('static', filename='wt-design/hrm.png') }}" alt=""></a>
                            </div>
                            <div class="box-title w-75 text-center font-weight-bold">
                                <a href="#" class="black-text">HUMAN RESOURCE
                                    MANAGEMENT</a>
                            </div>
                        </div>
                        <!-- First Box -->

                        <!-- Second Box -->
                        <div class="box-1 z-depth-1-half aqua-gradient d-flex flex-column align-items-center">
                            <div class="box-img mt-3">
                                <a href="{{ url_for('feedmill.feedoverview') }}"><img
                                        src="{{ url_for('static', filename='wt-design/feedcost.png') }}" alt=""></a>
                            </div>
                            <div class="box-title w-75 text-center font-weight-bold">
                                <a href="{{ url_for('feedmill.feedoverview') }}" class="black-text">FEED COST
                                    MANAGEMENT</a>
                            </div>
                        </div>
                        <!-- Second Box -->

                        <!-- Third Box -->
                        <div class="box-1 z-depth-1-half aqua-gradient d-flex flex-column align-items-center">
                            <div class="box-img mt-3">
                                <a href=""><img src="{{ url_for('static', filename='wt-design/procurement.png') }}"
                                        alt=""></a>
                            </div>
                            <div class="box-title w-75 text-center font-weight-bold">
                                <a href="#" class="black-text">PROCUREMENT MANAGEMENT</a>
                            </div>
                        </div>
                        <!-- Third Box -->

                        <!-- Fourth Box -->
                        <div class="box-1 z-depth-1-half aqua-gradient d-flex flex-column align-items-center">
                            <div class="box-img mt-3">
                                <a href="#"><img src="{{ url_for('static', filename='wt-design/sales.png') }}"
                                        alt=""></a>
                            </div>
                            <div class="box-title w-75 text-center font-weight-bold">
                                <a href="#" class="black-text">SALES MANAGEMENT</a>
                            </div>
                        </div>
                        <!-- Fourth Box -->

                        <!-- Fifth Box -->
                        <div class="box-1 z-depth-1-half aqua-gradient d-flex flex-column align-items-center">
                            <div class="box-img mt-3">
                                <a href="#"><img src="{{ url_for('static', filename='wt-design/store.png') }}"
                                        alt=""></a>
                            </div>
                            <div class="box-title w-75 text-center font-weight-bold">
                                <a href="{{ url_for('stores.store_portal') }}" class="black-text">STORE MANAGEMENT</a>
                            </div>
                        </div>
                        <!-- Fifth Box -->


                        <div class="box-1 z-depth-1-half aqua-gradient"></div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Portals -->

        <!-- Footer -->
        <footer>
            <div class="page-footer py-2">
                <div class="footer-copyright text-center">
                    <div class="footer-text white-text text-muted">@2019 All Rights Reserved | Developed by
                        WebTekNg</div>
                </div>
            </div>
        </footer>
        <!-- Footer -->

    </div>
    <!-- Main -->


    <!-- Scripts Goes Here -->
    <script src="{{url_for('static', filename='wt-js/main-dist.js')}}"></script>
    <script>
        //Handle Form Resubmission
        if (window.history.replaceState) {
            window.history.replaceState(null, null, window.location.href);
        }
    </script>
    <!-- Scripts Goes Here -->

</body>

</html>

automate/templates/main/profile.html
{% extends "layout/layout2.html" %}
{% from "macros/fields.html" import profile_form %}
{% from "macros/sidenav.html" import profile with context %}

{% block sidenav %}
{{ profile() }}
{% endblock sidenav %}


{% block content %}
<div class="col-md-10 offset-md-2 mt-3">

    <!-- Content -->
    <div class="content">

        <!-- Alert -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{category}} z-depth-1 py-2 mb-2">
            <span class="font-small">{{message}}</span>
            <a href="javascript:void(0)" data-dismiss="alert" class="close" style="font-size:0.9375rem;">&times;</a>
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <!-- Alert -->

        <!-- Welcome Row -->
        <div class="col-md-12 alert white mb-3 py-1 z-depth-1 d-flex justify-content-between align-items-center
            ">
            <div class="title">
                <h6 class="teal-text" style="font-size: 0.875rem">Welcome
                    {% if current_user.firstname %}
                    {{ current_user.firstname +" "+ current_user.lastname }}
                    {% else %}
                    {{ current_user.username }}
                    {% endif %}
                </h6>
            </div>
            <div class="datetime d-flex justify-content-around align-items-center flex-row">
                <!-- {{ date.today() }} -->
                <div class="row1">
                    <div class="day teal-text" style="font-size: 1.4375rem">{{ date.day }}</div>
                </div>
                &nbsp;
                <div class="row2 blue-grey-text" style="font-size: 0.8125rem">
                    <div class="month">{{ date.strftime("%b") }}.</div>
                    <div class="year">{{ date.year }}</div>
                </div>
                &nbsp;
                <div class="row3 font-small blue-grey-text" style="font-size: 0.8125rem">
                    <div class="time">{{ date.strftime("%H:%M:%S") }}</div>
                </div>
            </div>
        </div>
        <!-- Welcome Row -->

        <!-- First Row -->
        <div class="col-md-12 white py-3 z-depth-1 d-flex justify-content-between align-items-center">
            <div class="title">
                <h5 class="elegant-ic" style="font-size: 1.0938rem">User Profile..</h5>
            </div>
        </div>
        <!-- First Row -->

        <!-- Profile Row -->
        <div class="col-md-12 white mt-3 py-3 z-depth-1 d-flex justify-content-between align-items-center">
            <form action="" method="POST" enctype="multipart/form-data">
                <div class="teal-text font-small">You can update your profile here</div>
                {{ form.csrf_token }}

                <!-- Firstname -->
                {{ profile_form(form.firstname, placeholder="Enter Your Firstname") }}

                <!-- Lastname -->
                {{ profile_form(form.lastname, placeholder="Enter Your Lastname") }}

                <!-- Username -->
                {{ profile_form(form.username, placeholder="Enter Your Username") }}

                <!-- Email -->
                {{ profile_form(form.email, placeholder="Enter Your Email", disabled=disabled) }}

                <!-- Role -->
                {{ profile_form(form.role, value="Admin", disabled=disabled) }}

                <!-- Profile Picture -->
                {{ profile_form(form.picture) }}

                {{ form.submit(class='form-control teal white-ic font-small') }}
            </form>
        </div>
        <!-- Profile Row -->


    </div>
    <!-- Content -->

</div>
{% endblock content %}


{% block modal %}

{% endblock modal %}

automate/templates/main/wt_forget_password.html
{% extends "layout/layout1.html" %}
{% from "macros/fields.html" import render_field %}

{% block formcontent %}
<div class="col-md-6 offset-md-3">

    <!-- Alert Box -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} mt-4">
        <span class="font-weight-bold">{{message}}</span>
        <a href="javascript:void(0)" data-dismiss="alert" class="close">&times;</a>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="mt-3 z-depth-1-half p-3 form-box">
        <div class="white-text font-weight-bold mb-2 login-text">Forget Password!</div>

        <!-- Horizontal line -->
        <hr class="hr-light">

        <form action="" method="post" id="loginForm">
            {{ form.csrf_token }}
            <!--Email -->
            {{ render_field('envelope', form.email, placeholder='Enter Your Email...') }}

            <!-- Submit -->
            <div class="form-group">
                {{ form.submit(class="form-control teal darken-2 white-text font-weight-bold") }}
            </div>
        </form>

    </div>

</div>
{% endblock formcontent %}

automate/templates/main/wt_password_reset.html
{% extends "layout/layout1.html" %}
{% from "macros/fields.html" import render_field %}

{% block formcontent %}
<div class="col-md-6 offset-md-3">

    <!-- Alert Box -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} mt-4">
        <span class="font-weight-bold">{{message}}</span>
        <a href="javascript:void(0)" data-dismiss="alert" class="close">&times;</a>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="mt-3 z-depth-1-half p-3 form-box">
        <div class="white-text font-weight-bold mb-2 login-text">Password Reset!</div>

        <!-- Horizontal line -->
        <hr class="hr-light">

        <form action="" method="post" id="loginForm">
            {{ form.csrf_token }}
            <!-- Password -->
            {{ render_field('key', form.password, placeholder='Enter Your Password...') }}

            <!-- Confirm Password -->
            {{ render_field('key', form.confirm_password, placeholder='Enter Your Password...') }}

            <!-- Submit -->
            <div class="form-group">
                <input type="submit" value="RESET" class="form-control teal darken-2 white-text font-weight-bold">
            </div>
        </form>

    </div>

</div>
{% endblock formcontent %}

automate/templates/main/wt_signup.html
{% extends "layout/layout1.html" %}
{% from "macros/fields.html" import render_field %}

{% block formcontent %}
<div class="col-md-6 offset-md-3">

    <!-- Alert Box -->
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{category}} mt-4">
        <span class="font-weight-bold">{{message}}</span>
        <a href="javascript:void(0)" data-dismiss="alert" class="close">&times;</a>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="mt-3 z-depth-1-half p-3 form-box">
        <div class="white-text font-weight-bold mb-2 login-text">Signup to Access Database</div>

        <!-- Horizontal line -->
        <hr class="hr-light">

        <form action="" method="POST" id="loginForm">
            {{ form.csrf_token }}
            <!--Email -->
            {{ render_field('envelope', form.email, placeholder='Enter Email From Link...') }}

            <!-- Username -->
            {{ render_field('user', form.username, placeholder='Enter Your Username...') }}

            <!-- Password -->
            {{ render_field('key', form.password, placeholder='Enter Your Password...') }}

            <!-- Submit -->
            <div class="form-group">
                {{ form.submit(class="form-control teal darken-2 white-text font-weight-bold") }}
            </div>
        </form>
    </div>
</div>
{% endblock formcontent %}